"""empty message

Revision ID: d904fccde795
Revises: 18ee4eb439c0
Create Date: 2022-05-27 12:44:02.701645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd904fccde795'
down_revision = '18ee4eb439c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('isbn', table_name='user')
    op.drop_column('user', 'isbn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isbn', mysql.VARCHAR(length=120), nullable=False))
    op.create_index('isbn', 'user', ['isbn'], unique=False)
    # ### end Alembic commands ###
