"""empty message

Revision ID: f35859fc2e86
Revises: d904fccde795
Create Date: 2022-05-27 12:46:38.717485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35859fc2e86'
down_revision = 'd904fccde795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isbn', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isbn')
    # ### end Alembic commands ###
